<?php

namespace ContainerBhx4fS1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginFormComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Twig\Components\LoginFormComponent' autowired service.
     *
     * @return \App\Twig\Components\LoginFormComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ComponentWithFormTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'Components'.\DIRECTORY_SEPARATOR.'LoginFormComponent.php';

        $container->factories['App\\Twig\\Components\\LoginFormComponent'] = function () use ($container) {
            $instance = new \App\Twig\Components\LoginFormComponent();

            $instance->setContainer(($container->privates['.service_locator.CshazM0.App\\Twig\\Components\\LoginFormComponent'] ?? $container->load('getLoginFormComponent2Service')));

            return $instance;
        };

        return $container->factories['App\\Twig\\Components\\LoginFormComponent']();
    }
}
