<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSbJ4vrL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSbJ4vrL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSbJ4vrL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSbJ4vrL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSbJ4vrL\App_KernelDevDebugContainer([
    'container.build_hash' => 'SbJ4vrL',
    'container.build_id' => '62105a15',
    'container.build_time' => 1679876591,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSbJ4vrL');
