<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSaDDucp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSaDDucp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSaDDucp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSaDDucp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSaDDucp\App_KernelDevDebugContainer([
    'container.build_hash' => 'SaDDucp',
    'container.build_id' => '6f779a69',
    'container.build_time' => 1681731533,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSaDDucp');
